title_en: cr0hn Personal blog
permalink: /:categories/:year/:month/:day/:title
markdown: kramdown
baseurl: /blog
description_en: "Personal blog to write in it when I have head in the clouds."
keywords_en: "hacking, security, python"