url: "http://cr0hn.com"


# Build settings
#markdown: redcarpet
markdown: kramdown
permalink: pretty
highlighter: rouge


kramdown:
  input: GFM
  hard_wrap: false

#redcarpet:
#  extensions: ["tables", "autolink", "markdown"]
